version: "3.3"

services:
  cisgraderoom-api:
    container_name: cisgraderoom-api
    image: cisgraderoom/api
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    env_file:
      - ./.env
    volumes: 
      - .:/app
    ports:
        - "3000:3000"
    restart: always
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: 
      - ./.env
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    ports: 
      - "3306:3306"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  redis:
    image: redis:6.2.5-alpine
    restart: always
    hostname: redis
    container_name: redis
    ports: 
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
  redisinsights:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - ./data/redisinsight:/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    env_file: 
      - ./.env
    ports: 
      - "5672:5672"
      - "15672:15672"