version: "3.9"

services:
  ebook:
    container_name: cisclassroom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    restart: always
networks:
  localdev:
    external: true