version: "3.9"

services:
  cisgraderoom-api:
    container_name: cisgraderoom-api
    image: cisgraderoom/api
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    env_file:
      - ./.env
    volumes: 
      - .:/app
    ports:
        - "3000:3000"
    restart: always

networks:
  localdev:
    external: true